# Generated by Django 6.0.6 on 2026-06-15 10:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHIRPSDataFeed',
            fields=[
                ('datafeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.datafeed')),
                ('head_timeout', models.IntegerField(default=20, help_text='HTTP HEAD timeout (seconds) used for URL existence checks.')),
            ],
            options={
                'verbose_name': 'CHIRPS Data Feed',
            },
            bases=('georivasources.datafeed', models.Model),
        ),
        migrations.CreateModel(
            name='CHIRPSDataFeedCollectionLink',
            fields=[
                ('datafeedcollectionlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.datafeedcollectionlink')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('pentadal', 'Pentadal (5-day)'), ('dekadal', 'Dekadal (10-day)')], max_length=10)),
                ('default_start_date', models.DateField(default=datetime.date(1981, 1, 1), help_text='Default backfill start date for this collection.')),
            ],
            options={
                'verbose_name': 'CHIRPS Collection Link',
            },
            bases=('georivasources.datafeedcollectionlink',),
        ),
    ]
